# https://docs.codecov.com/docs/codecov-yaml
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
ignore:
  - "linkml_runtime/linkml_model/**/*"  # Vendored code from linkml-model
