"""Generate or verify the checksum manifest for the vendored linkml-model files.

``make update_model`` runs this after vendoring to write ``VENDORED_MANIFEST``
next to ``UPSTREAM_SHA``. The per-PR test suite runs it with ``--check`` to
catch vendored files that were edited without re-vendoring -- offline, so a
hand edit fails the PR immediately instead of waiting for the weekly upstream
comparison. The weekly job still compares against the pinned upstream commit,
which also guards the manifest itself against being regenerated by hand.

Hashes are computed over newline-normalised bytes: ``.gitattributes`` sets
``text=auto``, so working trees have CRLF on Windows and LF elsewhere; raw
bytes would give every text file a different digest per platform.
"""

import hashlib
import sys
from pathlib import Path

LINKML_MODEL_DIR = Path(__file__).resolve().parent / "src" / "linkml_runtime" / "linkml_model"
MANIFEST_FILE = LINKML_MODEL_DIR / "VENDORED_MANIFEST"

EXCLUDED = {
    MANIFEST_FILE.name,  # the manifest cannot list itself
    "__pycache__",
}


def _digest(path: Path) -> str:
    """Return the sha256 of ``path`` with CRLF normalised to LF."""
    return hashlib.sha256(path.read_bytes().replace(b"\r\n", b"\n")).hexdigest()


def _vendored_files() -> list[Path]:
    return sorted(
        p
        for p in LINKML_MODEL_DIR.rglob("*")
        if p.is_file() and p.name not in EXCLUDED and "__pycache__" not in p.parts and p.suffix != ".pyc"
    )


def generate() -> str:
    """Return the manifest content for the current vendored files."""
    lines = [f"{_digest(p)}  {p.relative_to(LINKML_MODEL_DIR).as_posix()}" for p in _vendored_files()]
    return "\n".join(lines) + "\n"


def check() -> list[str]:
    """Return a list of problems; empty means the vendored files match the manifest."""
    if not MANIFEST_FILE.exists():
        return [f"{MANIFEST_FILE} not found. Run 'make update_model' in packages/linkml_runtime/."]

    recorded = {}
    for line in MANIFEST_FILE.read_text().splitlines():
        digest, _, rel = line.partition("  ")
        recorded[rel] = digest

    problems = []
    current = {p.relative_to(LINKML_MODEL_DIR).as_posix(): _digest(p) for p in _vendored_files()}
    for rel in sorted(recorded.keys() - current.keys()):
        problems.append(f"missing (listed in manifest, not on disk): {rel}")
    for rel in sorted(current.keys() - recorded.keys()):
        problems.append(f"untracked (on disk, not in manifest): {rel}")
    for rel in sorted(recorded.keys() & current.keys()):
        if recorded[rel] != current[rel]:
            problems.append(f"modified: {rel}")
    return problems


def main() -> int:
    if "--check" in sys.argv:
        problems = check()
        for problem in problems:
            print(problem)
        return 1 if problems else 0
    MANIFEST_FILE.write_text(generate())
    print(f"Wrote {MANIFEST_FILE} ({len(_vendored_files())} files)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
