name: Build and test linkml-runtime with latest dependency versions

on:
  schedule:
    - cron: '0 5 * * 1'  # once per week on Monday at 05:00 UTC
  workflow_dispatch:
  # Allows you to run this workflow manually from the Actions tab
    types: trigger-run-check-dependencies

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.13"
          python-version: "3.13"
      - name: Install dependencies
        run: uv sync --group dev
      - name: Run codespell
        run: uv run codespell linkml_runtime tests
      - name: Run code quality checks
        run: uv run ruff check linkml_runtime tests

  test:
    needs:
      - quality-checks
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        exclude:
        - os: windows-latest
          python-version: "3.10"
        - os: windows-latest
          python-version: "3.11"
        - os: windows-latest
          python-version: "3.12"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.13"
          python-version: ${{ matrix.python-version }}


      - name: Check out repository
        uses: actions/checkout@v4.2.2
        with:
          # Fetch all history for all branches and all tags.
          # The tags are required for dynamic versioning.
          fetch-depth: 0

      - name: Install library
        run: uv sync --all-extras --dev

      - name: Regenerating uv.lock file & install (sync) dependencies
        run: |
          uv lock --upgrade
          uv sync

      - name: Run tests
        # Set bash shell to fail correctly on Windows https://github.com/actions/runner-images/issues/6668
        shell: bash
        run: uv run python -m pytest --with-slow
