name: Build and test linkml-runtime with latest dependency versions

on:
  schedule:
    - cron: '0 5 * * 1'  # once per week on Monday at 05:00 UTC
  workflow_dispatch:
  # Allows you to run this workflow manually from the Actions tab
    types: trigger-run-check-dependencies

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4.2.2
      - name: Install Poetry
        run: |
          pipx install poetry
          pipx inject poetry poetry-dynamic-versioning
      - uses: actions/setup-python@v5.6.0
        with:
          python-version: 3.13
      - name: Check pyproject.toml and poetry.lock
        run: poetry check
      - name: Install tox
        run: python -m pip install tox
      - name: Run codespell
        run: tox -e codespell
      - name: Run code quality checks
        run: tox -e lint

  test:
    needs:
      - quality-checks
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        exclude:
        - os: windows-latest
          python-version: "3.10"
        - os: windows-latest
          python-version: "3.11"
        - os: windows-latest
          python-version: "3.12"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Poetry
        run: |
          pipx install poetry
          pipx inject poetry poetry-dynamic-versioning

      - name: Check out repository
        uses: actions/checkout@v4.2.2
        with:
          # Fetch all history for all branches and all tags.
          # The tags are required for dynamic versioning.
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.6.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install library
        run: poetry install --no-interaction

      - name: Regenerating poetry.lock file & install (sync) dependencies
        run: |
          poetry lock --regenerate
          poetry sync

      - name: Run tests
        # Set bash shell to fail correctly on Windows https://github.com/actions/runner-images/issues/6668
        shell: bash
        run: poetry run python -m pytest --with-slow
