# Built from:
# https://github.com/actions/checkout/
# https://github.com/actions/setup-python/
# https://github.com/codecov/codecov-action

name: Build and test linkml-runtime

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.13"
          python-version: "3.13"
      - name: Install dependencies
        run: uv sync --group dev
      - name: Run codespell
        run: uv run codespell linkml_runtime tests
      - name: Run code format checks
        run: uv run ruff format --check linkml_runtime tests

  test:
    needs:
      - quality-checks
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        # Test on Windows with only the oldest and newest Python versions
        exclude:
          - os: windows-latest
            python-version: "3.10"
          - os: windows-latest
            python-version: "3.11"
          - os: windows-latest
            python-version: "3.12"
    # See https://github.com/snok/install-poetry#running-on-windows
    defaults:
      run:
        shell: bash

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.13"
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          python-version: ${{ matrix.python-version }}

      - name: Install library
        run: uv sync --all-extras --dev
      - name: Generate coverage results
        # Set bash shell to fail correctly on Windows https://github.com/actions/runner-images/issues/6668
        shell: bash
        run: |
          uv run coverage run -m pytest
          uv run coverage xml
          uv run coverage report -m
      - name: Upload coverage report
        uses: codecov/codecov-action@v5
        with:
          name: codecov-results-${{ matrix.os }}-${{ matrix.python-version }}
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
          fail_ci_if_error: false
