"""
Pydantic version of the LinkML metamodel, generated by pydanticgen.

PROVISIONAL: this module is the side-by-side pydantic counterpart of the
dataclass metamodel in :mod:`linkml_runtime.linkml_model.meta`. Its API may
change while core LinkML functionality migrates to it; the dataclass
metamodel remains the default and is unaffected.
"""

from linkml_runtime.linkml_model.pydantic.meta import *  # noqa: F401,F403
