# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      # Individual pull requests for major/minor updates and grouped for patch updates
      dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "patch"
    open-pull-requests-limit: 10
