rules:
  no_empty_title:
    level: disabled
  permissible_values_format:
    level: disabled
    format: uppersnake
  tree_root_class:
    level: disabled
    root_class_name: Container
    validate_existing_class_name: false
  recommended:
    level: disabled
    include: []
    exclude: []
  no_xsd_int_type:
    level: disabled
  no_invalid_slot_usage:
    level: disabled
  standard_naming:
    level: disabled
    permissible_values_upper_case: false
  canonical_prefixes:
    level: disabled
    prefixmaps_contexts:
      - merged
