"""Constants for compliance tests. See README.md for more information."""
from tests.test_compliance.helper import (
    JSON_SCHEMA,
    OWL,
    PYDANTIC,
    PYTHON_DATACLASSES,
    SHACL,
    SHEX,
    SQL_ALCHEMY_DECLARATIVE,
    SQL_ALCHEMY_IMPERATIVE,
    SQL_DDL_POSTGRES,
    SQL_DDL_SQLITE,
)

CLASS_CONTAINER = "Container"
CLASS_C = "C"
CLASS_D = "D"
CLASS_X = "X"
CLASS_Y = "Y"
CLASS_ANY = "Any"
CLASS_MC1 = "MC1"
CLASS_MC2 = "MC2"
SLOT_S1 = "s1"
SLOT_S2 = "s2"
SLOT_S3 = "s3"
SLOT_S4 = "s4"
SLOT_ID = "id"
EXAMPLE_STRING_VALUE_1 = "foo"
EXAMPLE_STRING_VALUE_2 = "bar"
EXAMPLE_STRING_VALUE_3 = "fuz"
EXAMPLE_STRING_VALUE_4 = "erk"

CORE_FRAMEWORKS = [
    PYTHON_DATACLASSES,
    PYDANTIC,
    JSON_SCHEMA,
    SHACL,
    SHEX,
    SQL_ALCHEMY_IMPERATIVE,
    SQL_ALCHEMY_DECLARATIVE,
    SQL_DDL_SQLITE,
    SQL_DDL_POSTGRES,
    OWL,
]
