"""
Regenerate the vendored pydantic metamodel in linkml_runtime.

The pydantic metamodel (``linkml_runtime.linkml_model.pydantic``) is generated
from the vendored metamodel schema YAML by pydanticgen and committed, exactly
like the dataclass ``linkml_model/meta.py`` artifact synced from linkml-model
releases. Run after every metamodel sync (see packages/linkml_runtime/Makefile).

Usage::

    uv run python scripts/generate_pydantic_metamodel.py
"""

from pathlib import Path

from linkml.generators.pydanticgen import PydanticGenerator

REPO_ROOT = Path(__file__).resolve().parent.parent
META_YAML = REPO_ROOT / "packages/linkml_runtime/src/linkml_runtime/linkml_model/model/schema/meta.yaml"
TARGET_DIR = REPO_ROOT / "packages/linkml_runtime/src/linkml_runtime/linkml_model/pydantic"

#: Canonical generator options for the vendored metamodel artifact. The
#: drift-guard test (tests/linkml/test_generators/test_pydanticgen_metamodel.py)
#: regenerates with these same options.
METAMODEL_GENERATOR_KWARGS: dict = {
    # SchemaView and other core consumers iterate container slots without
    # None-guards, matching the dataclass metamodel's empty_list/empty_dict
    # defaults; the base-model serializer omits empty containers on dump.
    "empty_list_for_multivalued_slots": True,
    # SchemaView.induced_slot assigns to slot copies in a tight loop;
    # re-validating every assignment costs ~4x on that hot path.
    "validate_assignment": False,
    # Reproduce YAMLRoot's permissive input normalization (key injection,
    # scalar wrapping, simple-dict forms) so schema YAML that loads under
    # the dataclass metamodel loads here too.
    "coerce_input": True,
}

HEADER = """\
# Vendored, generated file -- do not edit.
# Regenerate with: uv run python scripts/generate_pydantic_metamodel.py
# Source: linkml_runtime/linkml_model/model/schema/meta.yaml
"""

INIT = '''\
"""
Pydantic version of the LinkML metamodel, generated by pydanticgen.

PROVISIONAL: this module is the side-by-side pydantic counterpart of the
dataclass metamodel in :mod:`linkml_runtime.linkml_model.meta`. Its API may
change while core LinkML functionality migrates to it; the dataclass
metamodel remains the default and is unaffected.
"""

from linkml_runtime.linkml_model.pydantic.meta import *  # noqa: F401,F403
'''


def main() -> None:
    """Generate meta.py and __init__.py for the vendored pydantic metamodel."""
    source = PydanticGenerator(str(META_YAML), **METAMODEL_GENERATOR_KWARGS).serialize()
    TARGET_DIR.mkdir(parents=True, exist_ok=True)
    (TARGET_DIR / "meta.py").write_text(HEADER + source)
    (TARGET_DIR / "__init__.py").write_text(INIT)
    print(f"wrote {TARGET_DIR / 'meta.py'}")


if __name__ == "__main__":
    main()
