"""
Round-trip tests for the pydanticgen-generated metamodel.

The generated pydantic ``SchemaDefinition`` must load the raw metamodel YAML
(``meta.yaml``) and produce content semantically equivalent to the established
dataclass path (``SchemaView`` + ``schema_as_dict``). This is the feasibility
gate for replacing the pythongen dataclass metamodel with a pydantic one.
"""

from pathlib import Path
from typing import Any

import pytest
import yaml
from linkml_runtime.utils.compile_python import compile_python
from linkml_runtime.utils.schema_as_dict import schema_as_dict
from linkml_runtime.utils.schemaview import SchemaView

from linkml import LOCAL_METAMODEL_YAML_FILE
from linkml.generators.pydanticgen import PydanticGenerator

pytestmark = pytest.mark.pydanticgen


@pytest.fixture(scope="module")
def metamodel_schemaview() -> SchemaView:
    """SchemaView over the metamodel, without import merging (matches raw YAML)."""
    return SchemaView(LOCAL_METAMODEL_YAML_FILE, merge_imports=False)


@pytest.fixture(scope="module")
def metamodel_module():
    """The metamodel generated by pydanticgen, compiled to a python module."""
    source = PydanticGenerator(LOCAL_METAMODEL_YAML_FILE).serialize()
    return compile_python(source, "meta_pydantic")


@pytest.fixture(scope="module")
def metamodel_data() -> dict[str, Any]:
    """The raw metamodel YAML as plain python objects."""
    return yaml.safe_load(Path(LOCAL_METAMODEL_YAML_FILE).read_text())


@pytest.fixture(scope="module")
def key_slot_names(metamodel_schemaview: SchemaView) -> frozenset[str]:
    """Names of all identifier/key slots in the metamodel.

    These are injected into inlined-dict values on load but stripped again by
    ``schema_as_dict`` (the dict key already carries them), so they must be
    ignored when comparing the two round-trip paths.
    """
    names = set()
    for class_name in metamodel_schemaview.all_classes():
        id_slot = metamodel_schemaview.get_identifier_slot(class_name, use_key=True)
        if id_slot is not None:
            names.add(str(id_slot.name))
    return frozenset(names)


def _normalized(value: Any, key_slot_names: frozenset[str], parent_key: str | None = None) -> Any:
    """Drop empty containers/None and key fields that duplicate their dict key."""
    if isinstance(value, dict):
        out = {}
        for k, v in value.items():
            v = _normalized(v, key_slot_names, parent_key=k)
            if v is None or v == [] or v == {}:
                continue
            if k in key_slot_names and v == parent_key:
                continue
            out[k] = v
        return out
    if isinstance(value, list):
        return [_normalized(v, key_slot_names) for v in value]
    return value


def _diff_paths(a: Any, b: Any, path: str = "", diffs: list[str] | None = None) -> list[str]:
    """Recursively collect human-readable paths where two structures differ."""
    if diffs is None:
        diffs = []
    if isinstance(a, dict) and isinstance(b, dict):
        for k in sorted(set(a) | set(b)):
            if k not in a:
                diffs.append(f"{path}.{k}: only in pydantic dump: {str(b[k])[:80]}")
            elif k not in b:
                diffs.append(f"{path}.{k}: only in dataclass dump: {str(a[k])[:80]}")
            else:
                _diff_paths(a[k], b[k], f"{path}.{k}", diffs)
    elif isinstance(a, list) and isinstance(b, list):
        if len(a) != len(b):
            diffs.append(f"{path}: list length {len(a)} != {len(b)}")
        else:
            for i, (x, y) in enumerate(zip(a, b)):
                _diff_paths(x, y, f"{path}[{i}]", diffs)
    elif a != b:
        diffs.append(f"{path}: dataclass={str(a)[:60]!r} pydantic={str(b)[:60]!r}")
    return diffs


def test_vendored_pydantic_metamodel_in_sync() -> None:
    """The committed linkml_runtime.linkml_model.pydantic artifact matches regeneration.

    Regenerate with: uv run python scripts/generate_pydantic_metamodel.py
    """
    import linkml_runtime.linkml_model.pydantic as vendored

    committed = (Path(vendored.__file__).parent / "meta.py").read_text()
    regenerated = PydanticGenerator(LOCAL_METAMODEL_YAML_FILE).serialize()
    assert committed.endswith(regenerated), (
        "vendored pydantic metamodel is stale; run scripts/generate_pydantic_metamodel.py"
    )


def test_metamodel_validates(metamodel_module, metamodel_data: dict[str, Any]) -> None:
    """The generated pydantic SchemaDefinition accepts the raw metamodel YAML."""
    schema = metamodel_module.SchemaDefinition.model_validate(metamodel_data)
    assert set(schema.classes) == set(metamodel_data["classes"])
    assert set(schema.slots) == set(metamodel_data["slots"])
    assert set(schema.enums) == set(metamodel_data["enums"])


def test_metamodel_roundtrip_matches_dataclass_path(
    metamodel_module,
    metamodel_data: dict[str, Any],
    key_slot_names: frozenset[str],
) -> None:
    """meta.yaml -> pydantic -> dict is semantically equal to the dataclass path."""
    # fresh SchemaView: queries on a shared instance (e.g. get_identifier_slot)
    # annotate the underlying schema in place (from_schema), polluting the dump
    dataclass_dump = schema_as_dict(SchemaView(LOCAL_METAMODEL_YAML_FILE, merge_imports=False).schema)
    # provenance injected by the loader, not schema content
    dataclass_dump.pop("source_file", None)

    pydantic_dump = metamodel_module.SchemaDefinition.model_validate(metamodel_data).model_dump(exclude_none=True)

    diffs = _diff_paths(
        _normalized(dataclass_dump, key_slot_names),
        _normalized(pydantic_dump, key_slot_names),
    )
    assert diffs == [], "round-trip dumps differ:\n" + "\n".join(diffs[:50])
