name: Build and test documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'poetry'

      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      - name: Install dependencies
        run: poetry install --no-interaction --with docs -E black

      - name: Build docs
        working-directory: docs
        env:
          SPHINXOPTS: "-W --keep-going"
        run: poetry run make html
